#!/bin/sh

result=""
for therm in /sys/class/thermal/thermal_zone*
do
    temp=$(awk '{ printf "%.1f", $1/1000 }' "$therm"/temp)
    type=$(cat "$therm"/type)
    if [ -z "$result" ]; then
	    result="$type(${temp}𝇈C)"
    else
	    result="$result  $type(${temp}𝇈C)"
    fi
done
echo "$result"
